In [2]:
from glob import glob
import os
import re
import sys
import datetime
import numpy as np
import pandas as pd
from tqdm import tqdm
from func.utils import get_categorical_features, read_pkl_gzip, to_pkl_gzip, parallel_load_data, get_filename
from ieee_train import eval_train, eval_check_feature, valid_submit_prediction
from kaggle_utils import reduce_mem_usage, move_feature

In [4]:
base_train = read_pkl_gzip('../input/base_train.gz')
length = base_train.shape[0]
predLB947 = read_pkl_gzip('../output/pred_result/20190903_1520__CV0-9474818622326217__all_preds.gz').values[length:]
predLB942 = read_pkl_gzip('../output/pred_result/20190907_2230__CV0-9424189978392622__all_preds.gz').values[length:]
predLB9450 = read_pkl_gzip('../output/pred_result/20190907_1420__CV0-9450165574769895__all_preds.gz').values[length:]
predLB9451 = read_pkl_gzip('../output/pred_result/20190904_1751__CV0-9451153656067325__all_preds.gz').values[length:]
list_pred = [
    predLB947,
    predLB942,
    predLB9450,
    predLB9451,
]
print(np.corrcoef([predLB947, predLB942, predLB9450, predLB9451]))

for pred in list_pred:
    valid_submit_prediction(pred)

[[1.         0.94693878 0.95557815 0.96234528]
 [0.94693878 1.         0.97133124 0.95536148]
 [0.95557815 0.97133124 1.         0.96037588]
 [0.96234528 0.95536148 0.96037588 1.        ]]
* Check Corr with Past Submit.
  * LB0.9422 / 0.8916251606063541
  * LB0.9446 / 0.969888880006145
  * LB0.9501 / 0.9416000829810967
  * LB0.9518 / 0.9586703058561867
* Check Corr with Past Submit.
  * LB0.9422 / 0.8990332136166838
  * LB0.9446 / 0.9473878438216419
  * LB0.9501 / 0.9331243416874463
  * LB0.9518 / 0.9391774569156414
* Check Corr with Past Submit.
  * LB0.9422 / 0.8906836933220461
  * LB0.9446 / 0.9541176584507791
  * LB0.9501 / 0.9357600099723923
  * LB0.9518 / 0.9423585413740623
* Check Corr with Past Submit.
  * LB0.9422 / 0.8934371174295982
  * LB0.9446 / 0.9584228485084942
  * LB0.9501 / 0.9355639015028154
  * LB0.9518 / 0.946905913505522
